// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package client

import (
	"context"

	v1 "github.com/wingfeng/idxadmin/api/client/v1"
	"github.com/wingfeng/idxadmin/internal/service"
)

func (c *ControllerV1) Save(ctx context.Context, req *v1.SaveReq) (res *v1.SaveRes, err error) {

	err = service.Client().Save(ctx, *req)
	return &v1.SaveRes{}, err
}
func (c *ControllerV1) Page(ctx context.Context, req *v1.PageReq) (res *v1.PageRes, err error) {

	res, err = service.Client().List(ctx, *req)
	return res, err
}
func (c *ControllerV1) Get(ctx context.Context, req *v1.GetReq) (res *v1.GetRes, err error) {
	r, err := service.Client().Get(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	res = &v1.GetRes{
		Clients: *r,
	}
	return res, err
}
func (c *ControllerV1) Delete(ctx context.Context, req *v1.DeleteReq) (res *v1.DeleteRes, err error) {
	err = service.Client().Delete(ctx, req)
	return nil, err
}
func (c *ControllerV1) GetClientSecrets(ctx context.Context, req *v1.GetClientSecretsReq) (res *v1.GetClientSecretsRes, err error) {
	items, err := service.Client().GetSecrets(ctx, req)
	res = &v1.GetClientSecretsRes{
		Secrets: items,
	}
	return res, err
}
func (c *ControllerV1) GenerateSecret(ctx context.Context, req *v1.GenerateSecretReq) (res *v1.GenerateSecretRes, err error) {
	secret, err := service.Client().GenerateSecret(ctx, req)
	return &v1.GenerateSecretRes{
		Secret: secret,
	}, err
}
func (c *ControllerV1) DeleteSecret(ctx context.Context, req *v1.DeleteSecretReq) (res *v1.DeleteSecretRes, err error) {
	err = service.Client().DeleteSecret(ctx, req)
	return nil, err
}
