// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package scope

import (
	"github.com/wingfeng/idxadmin/api/scope"
)

type ControllerV1 struct{}

func NewV1() scope.IScopeV1 {
	return &ControllerV1{}
}
