// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalClientsDao is internal type for wrapping internal DAO implements.
type internalClientsDao = *internal.ClientsDao

// clientsDao is the data access object for table clients.
// You can define custom methods on it to extend its functionality as you wish.
type clientsDao struct {
	internalClientsDao
}

var (
	// Clients is globally public accessible object for table clients operations.
	Clients = clientsDao{
		internal.NewClientsDao(),
	}
)

// Fill with you ideas below.
