// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalClientPostLogoutRedirectUrisDao is internal type for wrapping internal DAO implements.
type internalClientPostLogoutRedirectUrisDao = *internal.ClientPostLogoutRedirectUrisDao

// clientPostLogoutRedirectUrisDao is the data access object for table client_post_logout_redirect_uris.
// You can define custom methods on it to extend its functionality as you wish.
type clientPostLogoutRedirectUrisDao struct {
	internalClientPostLogoutRedirectUrisDao
}

var (
	// ClientPostLogoutRedirectUris is globally public accessible object for table client_post_logout_redirect_uris operations.
	ClientPostLogoutRedirectUris = clientPostLogoutRedirectUrisDao{
		internal.NewClientPostLogoutRedirectUrisDao(),
	}
)

// Fill with you ideas below.
