// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalClientSecretsDao is internal type for wrapping internal DAO implements.
type internalClientSecretsDao = *internal.ClientSecretsDao

// clientSecretsDao is the data access object for table client_secrets.
// You can define custom methods on it to extend its functionality as you wish.
type clientSecretsDao struct {
	internalClientSecretsDao
}

var (
	// ClientSecrets is globally public accessible object for table client_secrets operations.
	ClientSecrets = clientSecretsDao{
		internal.NewClientSecretsDao(),
	}
)

// Fill with you ideas below.
