// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalClientCorsOriginsDao is internal type for wrapping internal DAO implements.
type internalClientCorsOriginsDao = *internal.ClientCorsOriginsDao

// clientCorsOriginsDao is the data access object for table client_cors_origins.
// You can define custom methods on it to extend its functionality as you wish.
type clientCorsOriginsDao struct {
	internalClientCorsOriginsDao
}

var (
	// ClientCorsOrigins is globally public accessible object for table client_cors_origins operations.
	ClientCorsOrigins = clientCorsOriginsDao{
		internal.NewClientCorsOriginsDao(),
	}
)

// Fill with you ideas below.
