// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalIdentityResourcesDao is internal type for wrapping internal DAO implements.
type internalIdentityResourcesDao = *internal.IdentityResourcesDao

// identityResourcesDao is the data access object for table identity_resources.
// You can define custom methods on it to extend its functionality as you wish.
type identityResourcesDao struct {
	internalIdentityResourcesDao
}

var (
	// IdentityResources is globally public accessible object for table identity_resources operations.
	IdentityResources = identityResourcesDao{
		internal.NewIdentityResourcesDao(),
	}
)

// Fill with you ideas below.
