// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalIdentityClaimsDao is internal type for wrapping internal DAO implements.
type internalIdentityClaimsDao = *internal.IdentityClaimsDao

// identityClaimsDao is the data access object for table identity_claims.
// You can define custom methods on it to extend its functionality as you wish.
type identityClaimsDao struct {
	internalIdentityClaimsDao
}

var (
	// IdentityClaims is globally public accessible object for table identity_claims operations.
	IdentityClaims = identityClaimsDao{
		internal.NewIdentityClaimsDao(),
	}
)

// Fill with you ideas below.
