// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalIdentityPropertiesDao is internal type for wrapping internal DAO implements.
type internalIdentityPropertiesDao = *internal.IdentityPropertiesDao

// identityPropertiesDao is the data access object for table identity_properties.
// You can define custom methods on it to extend its functionality as you wish.
type identityPropertiesDao struct {
	internalIdentityPropertiesDao
}

var (
	// IdentityProperties is globally public accessible object for table identity_properties operations.
	IdentityProperties = identityPropertiesDao{
		internal.NewIdentityPropertiesDao(),
	}
)

// Fill with you ideas below.
