// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalOrganizationUnitsDao is internal type for wrapping internal DAO implements.
type internalOrganizationUnitsDao = *internal.OrganizationUnitsDao

// organizationUnitsDao is the data access object for table organization_units.
// You can define custom methods on it to extend its functionality as you wish.
type organizationUnitsDao struct {
	internalOrganizationUnitsDao
}

var (
	// OrganizationUnits is globally public accessible object for table organization_units operations.
	OrganizationUnits = organizationUnitsDao{
		internal.NewOrganizationUnitsDao(),
	}
)

// Fill with you ideas below.
