// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalPersistedGrantsDao is internal type for wrapping internal DAO implements.
type internalPersistedGrantsDao = *internal.PersistedGrantsDao

// persistedGrantsDao is the data access object for table persisted_grants.
// You can define custom methods on it to extend its functionality as you wish.
type persistedGrantsDao struct {
	internalPersistedGrantsDao
}

var (
	// PersistedGrants is globally public accessible object for table persisted_grants operations.
	PersistedGrants = persistedGrantsDao{
		internal.NewPersistedGrantsDao(),
	}
)

// Fill with you ideas below.
