// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalScopesDao is internal type for wrapping internal DAO implements.
type internalScopesDao = *internal.ScopesDao

// scopesDao is the data access object for table scopes.
// You can define custom methods on it to extend its functionality as you wish.
type scopesDao struct {
	internalScopesDao
}

var (
	// Scopes is globally public accessible object for table scopes operations.
	Scopes = scopesDao{
		internal.NewScopesDao(),
	}
)

// Fill with you ideas below.
