// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalUserGroupsDao is internal type for wrapping internal DAO implements.
type internalUserGroupsDao = *internal.UserGroupsDao

// userGroupsDao is the data access object for table user_groups.
// You can define custom methods on it to extend its functionality as you wish.
type userGroupsDao struct {
	internalUserGroupsDao
}

var (
	// UserGroups is globally public accessible object for table user_groups operations.
	UserGroups = userGroupsDao{
		internal.NewUserGroupsDao(),
	}
)

// Fill with you ideas below.
