// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalUserLoginsDao is internal type for wrapping internal DAO implements.
type internalUserLoginsDao = *internal.UserLoginsDao

// userLoginsDao is the data access object for table user_logins.
// You can define custom methods on it to extend its functionality as you wish.
type userLoginsDao struct {
	internalUserLoginsDao
}

var (
	// UserLogins is globally public accessible object for table user_logins operations.
	UserLogins = userLoginsDao{
		internal.NewUserLoginsDao(),
	}
)

// Fill with you ideas below.
