// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/wingfeng/idxadmin/internal/dao/internal"
)

// internalUserRolesDao is internal type for wrapping internal DAO implements.
type internalUserRolesDao = *internal.UserRolesDao

// userRolesDao is the data access object for table user_roles.
// You can define custom methods on it to extend its functionality as you wish.
type userRolesDao struct {
	internalUserRolesDao
}

var (
	// UserRoles is globally public accessible object for table user_roles operations.
	UserRoles = userRolesDao{
		internal.NewUserRolesDao(),
	}
)

// Fill with you ideas below.
